// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjwzEPm5ELDuCZD6pq6L2D8dFEHN82-4',
    appId: '1:176310540848:web:43fc4fb794a60a46412bf5',
    messagingSenderId: '176310540848',
    projectId: 'pri-parqueos-8eaba',
    authDomain: 'pri-parqueos-8eaba.firebaseapp.com',
    storageBucket: 'pri-parqueos-8eaba.appspot.com',
    measurementId: 'G-R5TYNVXQDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSVO3EwgCjKcadRZRkQCHCCdtGmtFJsik',
    appId: '1:176310540848:android:0fa1fa527245ae62412bf5',
    messagingSenderId: '176310540848',
    projectId: 'pri-parqueos-8eaba',
    storageBucket: 'pri-parqueos-8eaba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUpvU45HMR7ifcIjGaD2k0CGdFZxa_smA',
    appId: '1:176310540848:ios:4e032cc1b8d90c94412bf5',
    messagingSenderId: '176310540848',
    projectId: 'pri-parqueos-8eaba',
    storageBucket: 'pri-parqueos-8eaba.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUpvU45HMR7ifcIjGaD2k0CGdFZxa_smA',
    appId: '1:176310540848:ios:5134963782f1f6c0412bf5',
    messagingSenderId: '176310540848',
    projectId: 'pri-parqueos-8eaba',
    storageBucket: 'pri-parqueos-8eaba.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
